- name: install wget
  yum: name=wget state=present

- name: create java directory
  file: path=/usr/java state=directory owner=root group=root mode=0775

- name: check jdk8 package downloaded
  command: test -f {{ dir }}/jdk-{{ jdk8_pkg_version }}-linux-x64.tar.gz
  register: jdk8_downloaded
  failed_when: jdk8_downloaded.rc not in [0, 1]
  changed_when: False

- name: Download jdk package
  command: > 
     wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" {{ download_url }} -O {{ dir }}/jdk-{{ jdk8_pkg_version }}-linux-x64.tar.gz
  when: jdk8_downloaded.rc == 1

- name: Extract Package
  command: >
    tar -xf {{ dir }}/jdk-{{ jdk8_pkg_version }}-linux-x64.tar.gz
    chdir=/usr/java
    creates={{ java_file }}
    
- name: make Java available to the system
  command: 'alternatives --install "/usr/bin/java" "java" "{{ java_file }}/bin/java" 2000'

